// ============================================================
// Handwriting Styles Configuration
// ============================================================
import type { HandwritingStyle } from "@/types";

export const HANDWRITING_STYLES: HandwritingStyle[] = [
  {
    id: "neat-student",
    label: "Neat Student",
    fontFamily: "'Caveat', cursive",
    fontSize: 22,
    strokeWidth: 1.5,
    letterSpacing: 0.02,
    lineHeight: 1.8,
    rotationRange: 1.5,
    baselineRange: 1.5,
    spacingJitter: 0.5,
    pressureVariation: 0.1,
    shakiness: 0.05,
    inkFade: 0.03,
    wordSpacingJitter: 1,
    slant: -2,
  },
  {
    id: "messy-student",
    label: "Messy Student",
    fontFamily: "'Architects Daughter', cursive",
    fontSize: 24,
    strokeWidth: 2,
    letterSpacing: -0.01,
    lineHeight: 1.75,
    rotationRange: 4,
    baselineRange: 4,
    spacingJitter: 3,
    pressureVariation: 0.3,
    shakiness: 0.3,
    inkFade: 0.07,
    wordSpacingJitter: 5,
    slant: 3,
  },
  {
    id: "fast-writing",
    label: "Fast Writing",
    fontFamily: "'Kalam', cursive",
    fontSize: 23,
    strokeWidth: 1.8,
    letterSpacing: 0.01,
    lineHeight: 1.7,
    rotationRange: 3,
    baselineRange: 3,
    spacingJitter: 2,
    pressureVariation: 0.25,
    shakiness: 0.2,
    inkFade: 0.08,
    wordSpacingJitter: 3,
    slant: -4,
  },
  {
    id: "elegant",
    label: "Elegant",
    fontFamily: "'Dancing Script', cursive",
    fontSize: 25,
    strokeWidth: 1.2,
    letterSpacing: 0.03,
    lineHeight: 1.9,
    rotationRange: 1,
    baselineRange: 1,
    spacingJitter: 0.5,
    pressureVariation: 0.15,
    shakiness: 0.02,
    inkFade: 0.04,
    wordSpacingJitter: 1.5,
    slant: -5,
  },
  {
    id: "teacher",
    label: "Teacher",
    fontFamily: "'Schoolbell', cursive",
    fontSize: 21,
    strokeWidth: 1.6,
    letterSpacing: 0.02,
    lineHeight: 1.85,
    rotationRange: 1.5,
    baselineRange: 1.5,
    spacingJitter: 1,
    pressureVariation: 0.12,
    shakiness: 0.06,
    inkFade: 0.03,
    wordSpacingJitter: 2,
    slant: -1,
  },
  {
    id: "female",
    label: "Female",
    fontFamily: "'Pacifico', cursive",
    fontSize: 22,
    strokeWidth: 1.3,
    letterSpacing: 0.04,
    lineHeight: 1.95,
    rotationRange: 2,
    baselineRange: 2,
    spacingJitter: 1,
    pressureVariation: 0.1,
    shakiness: 0.04,
    inkFade: 0.04,
    wordSpacingJitter: 2,
    slant: -3,
  },
  {
    id: "male",
    label: "Male",
    fontFamily: "'Patrick Hand', cursive",
    fontSize: 22,
    strokeWidth: 2,
    letterSpacing: 0.01,
    lineHeight: 1.75,
    rotationRange: 2.5,
    baselineRange: 2.5,
    spacingJitter: 1.5,
    pressureVariation: 0.2,
    shakiness: 0.1,
    inkFade: 0.05,
    wordSpacingJitter: 2.5,
    slant: 1,
  },
  {
    id: "child",
    label: "Child",
    fontFamily: "'Chewy', cursive",
    fontSize: 26,
    strokeWidth: 2.5,
    letterSpacing: 0.05,
    lineHeight: 2.1,
    rotationRange: 6,
    baselineRange: 6,
    spacingJitter: 5,
    pressureVariation: 0.4,
    shakiness: 0.4,
    inkFade: 0.09,
    wordSpacingJitter: 7,
    slant: 5,
  },
  {
    id: "sketchy",
    label: "Sketchy",
    fontFamily: "'Reenie Beanie', cursive",
    fontSize: 24,
    strokeWidth: 1.4,
    letterSpacing: 0.02,
    lineHeight: 1.8,
    rotationRange: 5,
    baselineRange: 4,
    spacingJitter: 3,
    pressureVariation: 0.35,
    shakiness: 0.35,
    inkFade: 0.1,
    wordSpacingJitter: 4,
    slant: 2,
  },
  {
    id: "engineering",
    label: "Engineering",
    fontFamily: "'Share Tech Mono', monospace",
    fontSize: 18,
    strokeWidth: 1.2,
    letterSpacing: 0.05,
    lineHeight: 1.6,
    rotationRange: 0.5,
    baselineRange: 0.5,
    spacingJitter: 0.2,
    pressureVariation: 0.05,
    shakiness: 0.02,
    inkFade: 0.02,
    wordSpacingJitter: 0.5,
    slant: 0,
  },
  {
    id: "medical",
    label: "Medical Notes",
    fontFamily: "'Rock Salt', cursive",
    fontSize: 19,
    strokeWidth: 2.2,
    letterSpacing: -0.02,
    lineHeight: 1.65,
    rotationRange: 6,
    baselineRange: 5,
    spacingJitter: 4,
    pressureVariation: 0.45,
    shakiness: 0.45,
    inkFade: 0.12,
    wordSpacingJitter: 6,
    slant: -6,
  },
];

export const DEFAULT_STYLE_ID = "neat-student";

export const getStyle = (id: string): HandwritingStyle =>
  HANDWRITING_STYLES.find((s) => s.id === id) ?? HANDWRITING_STYLES[0];
