// ============================================================
// Notebook Templates Configuration
// ============================================================
import type { NotebookTemplate } from "@/types";

export const NOTEBOOK_TEMPLATES: NotebookTemplate[] = [
  {
    id: "classic-white",
    label: "Classic White",
    category: "Standard",
    paperColor: "#ffffff",
    lineColor: "#c8d6e8",
    marginColor: "#f4a4a4",
    lineSpacing: 32,
    marginLeft: 70,
    marginRight: 40,
    marginTop: 50,
    marginBottom: 40,
    hasLines: true,
    hasMargin: true,
    hasGrid: false,
    hasHoles: true,
    paperTexture: "smooth",
    shadowIntensity: 0.3,
    description: "Classic lined notebook paper with red margin",
  },
  {
    id: "blue-ruled",
    label: "Blue Ruled",
    category: "Standard",
    paperColor: "#f0f6ff",
    lineColor: "#98bfe0",
    marginColor: "#e88080",
    lineSpacing: 30,
    marginLeft: 65,
    marginRight: 35,
    marginTop: 48,
    marginBottom: 38,
    hasLines: true,
    hasMargin: true,
    hasGrid: false,
    hasHoles: true,
    paperTexture: "smooth",
    shadowIntensity: 0.25,
    description: "Blue-tinted ruled paper",
  },
  {
    id: "legal-pad",
    label: "Yellow Legal Pad",
    category: "Legal",
    paperColor: "#fefce8",
    lineColor: "#c5b85a",
    marginColor: "#e88080",
    lineSpacing: 28,
    marginLeft: 60,
    marginRight: 35,
    marginTop: 45,
    marginBottom: 35,
    hasLines: true,
    hasMargin: true,
    hasGrid: false,
    hasHoles: false,
    paperTexture: "smooth",
    shadowIntensity: 0.2,
    description: "Classic yellow legal pad",
  },
  {
    id: "grid",
    label: "Grid Notebook",
    category: "Technical",
    paperColor: "#fafafa",
    lineColor: "#c8d8e8",
    marginColor: "#c8d8e8",
    lineSpacing: 20,
    marginLeft: 30,
    marginRight: 30,
    marginTop: 30,
    marginBottom: 30,
    hasLines: false,
    hasMargin: false,
    hasGrid: true,
    hasHoles: false,
    gridSize: 20,
    paperTexture: "clean",
    shadowIntensity: 0.2,
    description: "Engineering grid paper",
  },
  {
    id: "campus",
    label: "Campus Notebook",
    category: "Student",
    paperColor: "#ffffff",
    lineColor: "#b8d0e8",
    marginColor: "#f0a8a8",
    lineSpacing: 26,
    marginLeft: 80,
    marginRight: 30,
    marginTop: 60,
    marginBottom: 40,
    hasLines: true,
    hasMargin: true,
    hasGrid: false,
    hasHoles: true,
    paperTexture: "smooth",
    shadowIntensity: 0.35,
    description: "Japanese campus-style notebook",
  },
  {
    id: "binder",
    label: "Binder Paper",
    category: "Standard",
    paperColor: "#fefefe",
    lineColor: "#b0ccee",
    marginColor: "#e89090",
    lineSpacing: 31,
    marginLeft: 70,
    marginRight: 35,
    marginTop: 55,
    marginBottom: 40,
    hasLines: true,
    hasMargin: true,
    hasGrid: false,
    hasHoles: true,
    paperTexture: "rough",
    shadowIntensity: 0.3,
    description: "3-ring binder filler paper",
  },
  {
    id: "exam",
    label: "Exam Paper",
    category: "Academic",
    paperColor: "#fff9f0",
    lineColor: "#c0c0c0",
    marginColor: "#c0c0c0",
    lineSpacing: 28,
    marginLeft: 50,
    marginRight: 50,
    marginTop: 80,
    marginBottom: 50,
    hasLines: true,
    hasMargin: false,
    hasGrid: false,
    hasHoles: false,
    paperTexture: "smooth",
    shadowIntensity: 0.15,
    description: "Formal exam/test paper",
  },
  {
    id: "college-ruled",
    label: "College Ruled",
    category: "Standard",
    paperColor: "#ffffff",
    lineColor: "#a8c8e8",
    marginColor: "#f49898",
    lineSpacing: 24,
    marginLeft: 68,
    marginRight: 35,
    marginTop: 50,
    marginBottom: 38,
    hasLines: true,
    hasMargin: true,
    hasGrid: false,
    hasHoles: true,
    paperTexture: "smooth",
    shadowIntensity: 0.28,
    description: "Narrow-spaced college ruled",
  },
  {
    id: "wide-ruled",
    label: "Wide Ruled",
    category: "Standard",
    paperColor: "#ffffff",
    lineColor: "#b0d0f0",
    marginColor: "#f4a8a8",
    lineSpacing: 38,
    marginLeft: 72,
    marginRight: 40,
    marginTop: 55,
    marginBottom: 42,
    hasLines: true,
    hasMargin: true,
    hasGrid: false,
    hasHoles: true,
    paperTexture: "smooth",
    shadowIntensity: 0.28,
    description: "Wide-ruled paper for big handwriting",
  },
  {
    id: "blank",
    label: "Blank Paper",
    category: "Minimal",
    paperColor: "#ffffff",
    lineColor: "transparent",
    marginColor: "transparent",
    lineSpacing: 30,
    marginLeft: 50,
    marginRight: 50,
    marginTop: 50,
    marginBottom: 50,
    hasLines: false,
    hasMargin: false,
    hasGrid: false,
    hasHoles: false,
    paperTexture: "smooth",
    shadowIntensity: 0.15,
    description: "Plain blank paper",
  },
  {
    id: "pastel",
    label: "Cute Pastel",
    category: "Fun",
    paperColor: "#fff0f6",
    lineColor: "#f4c8dc",
    marginColor: "#f4a8c8",
    lineSpacing: 30,
    marginLeft: 60,
    marginRight: 40,
    marginTop: 50,
    marginBottom: 40,
    hasLines: true,
    hasMargin: false,
    hasGrid: false,
    hasHoles: false,
    paperTexture: "smooth",
    shadowIntensity: 0.18,
    description: "Cute pink pastel notebook",
  },
  {
    id: "japanese",
    label: "Japanese Notebook",
    category: "International",
    paperColor: "#f8fbff",
    lineColor: "#90b8d8",
    marginColor: "transparent",
    lineSpacing: 22,
    marginLeft: 30,
    marginRight: 30,
    marginTop: 40,
    marginBottom: 40,
    hasLines: true,
    hasMargin: false,
    hasGrid: false,
    hasHoles: false,
    paperTexture: "smooth",
    shadowIntensity: 0.2,
    description: "Clean Japanese B5 style",
  },
  {
    id: "vintage",
    label: "Vintage Notebook",
    category: "Special",
    paperColor: "#f5e8c8",
    lineColor: "#c8a870",
    marginColor: "#b88860",
    lineSpacing: 28,
    marginLeft: 55,
    marginRight: 40,
    marginTop: 50,
    marginBottom: 40,
    hasLines: true,
    hasMargin: true,
    hasGrid: false,
    hasHoles: false,
    paperTexture: "aged",
    shadowIntensity: 0.4,
    description: "Old vintage journal paper",
  },
  {
    id: "homework",
    label: "Homework Sheet",
    category: "Academic",
    paperColor: "#fefefe",
    lineColor: "#bfd0e8",
    marginColor: "#e89898",
    lineSpacing: 30,
    marginLeft: 70,
    marginRight: 40,
    marginTop: 90,
    marginBottom: 40,
    hasLines: true,
    hasMargin: true,
    hasGrid: false,
    hasHoles: true,
    paperTexture: "smooth",
    shadowIntensity: 0.25,
    description: "Standard homework assignment sheet",
  },
  // ============================================================
  // Boss Notebook — Indonesian SMA/SMP style
  // Exactly like the photo: checkboxes, header, warm desk
  // ============================================================
  {
    id: "boss-notebook",
    label: "Boss Notebook (Indonesia)",
    category: "Indonesia",
    paperColor: "#ffffff",
    lineColor: "#c0cce0",
    marginColor: "#e0e0e8",
    lineSpacing: 28,
    marginLeft: 68,
    marginRight: 30,
    marginTop: 110,  // big header area at top
    marginBottom: 30,
    hasLines: true,
    hasMargin: false,
    hasGrid: false,
    hasHoles: false,
    hasHeader: true,
    hasCheckboxes: true,
    paperTexture: "smooth",
    shadowIntensity: 0.35,
    deskColor: "#c9a96e", // warm wooden desk
    description: "Indonesian SMA boss notebook — checkboxes, header, wooden desk",
  },
];

export const DEFAULT_TEMPLATE_ID = "boss-notebook";


export const getTemplate = (id: string): NotebookTemplate =>
  NOTEBOOK_TEMPLATES.find((t) => t.id === id) ?? NOTEBOOK_TEMPLATES[0];

export const getTemplatesByCategory = (): Record<string, NotebookTemplate[]> => {
  return NOTEBOOK_TEMPLATES.reduce(
    (acc, t) => {
      if (!acc[t.category]) acc[t.category] = [];
      acc[t.category].push(t);
      return acc;
    },
    {} as Record<string, NotebookTemplate[]>
  );
};
