"use client";
import { useState, useCallback, useEffect } from "react";
import type { AppState, ExportFormat, ExportQuality, HeaderInfo } from "@/types";
import { DEFAULT_STYLE_ID } from "@/lib/styles-config";
import { DEFAULT_TEMPLATE_ID } from "@/lib/templates-config";
import { DEFAULT_INK_ID } from "@/lib/ink-config";

const DEFAULT_TEXT = `This is a sample handwriting demonstration for Malas Nulis.

The quick brown fox jumps over the lazy dog. This sentence contains every letter of the alphabet, making it perfect for testing handwriting styles.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.

Mathematics is fascinating: The area of a circle is A = πr², and Einstein's famous equation E = mc² changed our understanding of the universe.

Malas Nulis transforms your typed text into realistic handwriting that looks like it was written by a real person, not generated by a computer.`;

export function useAppState() {
  const [state, setState] = useState<AppState>({
    text: DEFAULT_TEXT,
    headerInfo: {
      name: "",
      class: "",
      no: "",
      date: "",
    },
    handwritingStyleId: DEFAULT_STYLE_ID,
    templateId: DEFAULT_TEMPLATE_ID,
    inkColorId: DEFAULT_INK_ID,
    effects: {
      noise: false,
      wrinkles: false,
      coffeeStain: false,
      oldPaper: false,
      shadow: true,
      curl: false,
      scanner: false,
      camera: false,
    },
    zoom: 1,
    currentPage: 0,
    isFullscreen: false,
    isDarkMode: true,
    pages: [],
    exportFormat: "png",
    exportQuality: "web",
    customFont: null,
    seed: 42,
  });

  const updateText = useCallback((text: string) => {
    setState((prev) => ({ ...prev, text, currentPage: 0 }));
  }, []);

  const updateStyle = useCallback((handwritingStyleId: string) => {
    setState((prev) => ({ ...prev, handwritingStyleId }));
  }, []);

  const updateTemplate = useCallback((templateId: string) => {
    setState((prev) => ({ ...prev, templateId }));
  }, []);

  const updateInk = useCallback((inkColorId: string) => {
    setState((prev) => ({ ...prev, inkColorId }));
  }, []);

  const toggleEffect = useCallback((effect: keyof AppState["effects"]) => {
    setState((prev) => ({
      ...prev,
      effects: { ...prev.effects, [effect]: !prev.effects[effect] },
    }));
  }, []);

  const updateZoom = useCallback((zoom: number) => {
    setState((prev) => ({ ...prev, zoom }));
  }, []);

  const setCurrentPage = useCallback((currentPage: number) => {
    setState((prev) => ({ ...prev, currentPage }));
  }, []);

  const toggleFullscreen = useCallback(() => {
    setState((prev) => ({ ...prev, isFullscreen: !prev.isFullscreen }));
  }, []);

  const toggleDarkMode = useCallback(() => {
    setState((prev) => ({ ...prev, isDarkMode: !prev.isDarkMode }));
  }, []);

  const updateHeaderInfo = useCallback((field: keyof HeaderInfo, value: string) => {
    setState((prev) => ({
      ...prev,
      headerInfo: { ...prev.headerInfo, [field]: value },
    }));
  }, []);

  const updatePages = useCallback((pages: AppState["pages"]) => {
    setState((prev) => ({ ...prev, pages }));
  }, []);

  const setExportFormat = useCallback((exportFormat: ExportFormat) => {
    setState((prev) => ({ ...prev, exportFormat }));
  }, []);

  const setExportQuality = useCallback((exportQuality: ExportQuality) => {
    setState((prev) => ({ ...prev, exportQuality }));
  }, []);

  const setCustomFont = useCallback((customFont: AppState["customFont"]) => {
    setState((prev) => ({ ...prev, customFont }));
  }, []);

  const randomize = useCallback(() => {
    const styles = ["neat-student", "messy-student", "fast-writing", "elegant", "teacher", "female", "male", "child", "sketchy", "engineering", "medical"];
    const templates = ["classic-white", "blue-ruled", "legal-pad", "grid", "campus", "binder", "exam", "college-ruled", "wide-ruled", "blank", "pastel", "japanese", "vintage", "homework"];
    const inks = ["blue", "black", "dark-blue", "purple", "green", "red", "pencil"];

    setState((prev) => ({
      ...prev,
      handwritingStyleId: styles[Math.floor(Math.random() * styles.length)],
      templateId: templates[Math.floor(Math.random() * templates.length)],
      inkColorId: inks[Math.floor(Math.random() * inks.length)],
      seed: Math.floor(Math.random() * 999999),
    }));
  }, []);

  const regenerate = useCallback(() => {
    setState((prev) => ({ ...prev, seed: Math.floor(Math.random() * 999999) }));
  }, []);

  useEffect(() => {
    if (state.isDarkMode) {
      document.documentElement.classList.add("dark");
    } else {
      document.documentElement.classList.remove("dark");
    }
  }, [state.isDarkMode]);

  return {
    state,
    updateText,
    updateHeaderInfo,
    updateStyle,
    updateTemplate,
    updateInk,
    toggleEffect,
    updateZoom,
    setCurrentPage,
    toggleFullscreen,
    toggleDarkMode,
    updatePages,
    setExportFormat,
    setExportQuality,
    setCustomFont,
    randomize,
    regenerate,
  };
}
